apiVersion: v1
kind: Secret
metadata:
  name: library-secrets
  namespace: library
type: Opaque
stringData:
  SECRET_KEY: "change-me-to-a-real-secret-key-in-production"
  DB_PASSWORD: "library_pass"
  RABBITMQ_PASSWORD: "library_pass"
