# Generated by Django 6.0.2 on 2026-02-22 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="books.book",
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["book", "rate"], name="books_ratin_book_id_f209a4_idx"
            ),
        ),
    ]
