# Generated by Django 6.0.2 on 2026-03-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_genre_expand_book_expand_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAnalytics',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytics', serialize=False, to='books.book')),
                ('avg_rating', models.FloatField(default=0.0)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('total_reservations', models.PositiveIntegerField(default=0)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'book analytics',
                'db_table': 'book_analytics',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_log_entity__c2633a_idx'), models.Index(fields=['timestamp'], name='audit_log_timesta_e8e14e_idx'), models.Index(fields=['user_id'], name='audit_log_user_id_4dac76_idx')],
            },
        ),
    ]
